build: remove Dockerfile and add codespace config
gymrek-lab/TRTools pull request #199
Opened 2023-12-16 06:21 UTC by aryarm

This PR removes our now-defunct Dockerfile. Instead, we recommend that you use the TRTools image maintained by the Bioconda team on the biocontainers registry. The docs have been updated to reflect this.

This PR also adds configuration for GitHub codepsaces! This can be helpful when you want to quickly play around with our code but don't want to go through all of the setup steps. Just click on the "Open in Github Codespaces" badge and voila - you'll be presented with an environment automagically set up with TRTools and our development dependencies. This environment will run with (usually free) credits on Github's codespace VMs.

Finally, this PR also specifies a strategy for our support for various python versions. From now on, we will only formally support active versions of python that are not end-of-life (3.8+). However, at least for now, we think that TRTools will still run properly for versions 3.6 and 3.7 - although support for those versions is not guaranteed and may break at any time.

2023-12-16 06:42 UTC, aryarm commented
@aarushi03, can I request your review on this PR, since you've worked with GitHub codespaces before? Can you try out the new badge (checked out to the `build/Dockerfile` branch) and let me know if it works for you?

[<img src="https://github.com/gymrek-lab/TRTools/assets/23412689/4667ed63-58c0-4078-9d74-c3ef4f6c1c2d">](https://codespaces.new/gymrek-lab/TRTools?ref=build%2FDockerfile)

2023-12-16 07:44 UTC, aarushi03 commented
> @aarushi03, can I request your review on this PR, since you've worked with GitHub codespaces before? Can you try out the new badge ([checked out to the `build/Dockerfile` branch](https://github.com/gymrek-lab/TRTools/tree/build/Dockerfile#trtools)) and let me know if it works for you?
> 
> [![](https://private-user-images.githubusercontent.com/23412689/290976876-4667ed63-58c0-4078-9d74-c3ef4f6c1c2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MTI5NjQsIm5iZiI6MTcwMjcxMjY2NCwicGF0aCI6Ii8yMzQxMjY4OS8yOTA5NzY4NzYtNDY2N2VkNjMtNThjMC00MDc4LTlkNzQtYzNlZjRmNmMxYzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDA3NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YzNjNmRkOWU1Nzc0NzNkNDFkYTM0YTFlMTkxMTI0MWUxMmNhYzYxOWRiODZiYWEyODQ0NGQ5MDY5NTkxMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.clIPM7HT9HFafL3Bo1fBJB8nYP1zDh3dig96xqUEDbE)](https://codespaces.new/gymrek-lab/TRTools?ref=build%2FDockerfile)

Certainly. Reviewing it now.

2023-12-16 07:51 UTC, aarushi03 commented on .devcontainer/environment.yml
Will -conda-forge::python=3.8 only allow it to be compatible with python 3.8 or even higher versions of python?

2023-12-16 08:03 UTC, aarushi03 requested changes

2023-12-16 08:03 UTC, aarushi03 commented on .devcontainer/environment.yml
Will -conda-forge::python=3.8 only allow it to be compatible with python 3.8 or even higher versions of python?

2023-12-16 08:03 UTC, aarushi03 commented on README.rst
> +
Add "Run the following command:"

2023-12-16 17:53 UTC, aryarm commented on README.rst
> +Please refer to `the biocontainers registry for TRTools <https://biocontainers.pro/tools/trtools>`_::
```suggestion
Please refer to `the biocontainers registry for TRTools <https://biocontainers.pro/tools/trtools>`_ for all of our images. To use the most recent release, run the following command::
```

2023-12-16 17:55 UTC, aryarm commented on .devcontainer/environment.yml
yes! this ensures that python 3.8 is the version that gets used during development, which will reduce the chance of the developer introducing a change that breaks support for our lowest supported version

I've added a comment that explains that within the yml file

2023-12-17 07:03 UTC, aarushi03 approved these changes

2023-12-19 19:47 UTC, merged